### ISSUE TITLE
Issue with en-passant in FEN

### ISSUE THREAD

**Issue by ageneau** [romstad/clj-chess#1]
According to https://chessprogramming.wikispaces.com/Forsyth-Edwards+Notation#Enpassanttargetsquare: "The en passant target square is specified after a double push of a pawn, no matter whether an en passant capture is really possible or not. Other moves than double pawn pushes imply the symbol '-' for this FEN field".

This means that:
`
(-> (new-game) (add-san-move "d4") board to-fen)
`
which currently returns "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1" should actually return "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq d3 0 1".

**Comment by romstad** [comment]
Wow, I never thought anyone out there in the real world used this totally unannounced and undocumented library. We use it internally at my job, and I always wanted it to be usable to a wider audience in the long run, but since it's still a bit immature, I've intentionally stayed quiet about it so far. Seems like it's still possible for people to discover it, and that it's time to clean things up and add some documentation!

You are right, en passant captures in FEN strings are not quite correct. I consider this a bug in the FEN specification (having the en passant capture square there when no en passant capture is possible seems wrong), but since the FEN standard isn't likely to ever get updated, I should probably change things to match the spec.

Thanks for reporting! And since you appear to be our first real world user: Suggestions and feature requests are most welcome.

**Comment by romstad** [comment]
Should work now. I also released a new 0.4.0 version (the previous non-snapshot version was *very* outdated and buggy).

**Comment by ageneau** [comment]
Thanks for the very quick fix!

I'm using clj-chess for this (side) project: https://github.com/ageneau/clchess. I started it using chess.js but then I discovered clj-chess existed (searched "chess" in clojars I think) so I'm in the process of switching the implementation (clj-chess branch in my project, still in progress).

Thanks for making it available.
